name: Containerize, push to Docker registry and run on remote server 

on:
  push:
    branches:
      - 'master'

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      -
        shell: bash
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SERVER_DEPLOY }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh root@${{ secrets.SERVER_IP }} "rm -rf website"
          ssh root@${{ secrets.SERVER_IP }} "git clone ${{ TO_CLONE }}"
          ssh root@${{ secrets.SERVER_IP }} "cd website && npm i && npm run build"
          ssh root@${{ secrets.SERVER_IP }} "cd website && export HOST=${{ HOST }} && export PORT=${{ PORT }} && npm run start"
